services:
  narou-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: narou-proxy
    restart: always
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
